/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Aplicacion.TarjetaCredito;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DAW-B
 */
public class AñadirModificarTarjeta extends javax.swing.JFrame {

    int posicion;
    private TarjetasJTable lista = new TarjetasJTable();
    TarjetasJTable.ModeloListaTarjetas modelo = lista.getModelo();
    //private boolean aceptado;

    /**
     * Creates new form AñadirModificarTarjeta
     */
    public AñadirModificarTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jbCrear = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGetionar = new javax.swing.JButton();
        jbGastos = new javax.swing.JButton();
        jbTarjetas = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCargarTarjetas = new javax.swing.JMenuItem();
        jmiExportarTarjetas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitulo.setText("¡BIENVENIDO!");

        jbCrear.setText("Crear Tarjeta");
        jbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar Tarjeta");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGetionar.setText("Gestionar Tarjeta");
        jbGetionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetionarActionPerformed(evt);
            }
        });

        jbGastos.setText("Gastos Tarjeta");
        jbGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGastosActionPerformed(evt);
            }
        });

        jbTarjetas.setText("Ver tarjetas");
        jbTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarjetasActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivos");

        jmiCargarTarjetas.setText("Cargar tarjetas");
        jmiCargarTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarTarjetasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCargarTarjetas);

        jmiExportarTarjetas.setText("Exportar tarjetas");
        jmiExportarTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExportarTarjetasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExportarTarjetas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGetionar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jbGastos, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jbTarjetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addComponent(jbCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbGetionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExportarTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExportarTarjetasActionPerformed
        try {
            FileOutputStream archivo = new FileOutputStream("tarjetas.txt");
            ObjectOutputStream salida = new ObjectOutputStream(archivo);

            salida.writeObject(modelo.getListatarjetas());

            salida.close();
            archivo.close();

            System.out.println("Se han guardado correctamente las tarjetas.");

        } catch (IOException ioe) {
            System.out.println("Error al escribir en el archivo.");
        }
    }//GEN-LAST:event_jmiExportarTarjetasActionPerformed

    private void jmiCargarTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarTarjetasActionPerformed
        ArrayList<TarjetaCredito> tarjetas = new ArrayList<>();
        try {
            FileInputStream archivo = new FileInputStream("tarjetas.txt");
            ObjectInputStream entrada = new ObjectInputStream(archivo);

            tarjetas = (ArrayList) entrada.readObject();
            modelo.setListatarjetas(tarjetas);
            entrada.close();
            archivo.close();

            System.out.println("Se ha deserializado el array desde el archivo:");

        } catch (IOException e) {
            System.out.println("Error al leer el archivo.");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AñadirModificarTarjeta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jmiCargarTarjetasActionPerformed

    private void jbTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarjetasActionPerformed
        lista.setVisible(true);
    }//GEN-LAST:event_jbTarjetasActionPerformed

    private void jbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearActionPerformed
        JDcrearTarjeta nuevaTarjeta = new JDcrearTarjeta(this, true);
        nuevaTarjeta.setVisible(true);

        //TarjetaCredito tarjeta = new TarjetaCredito("Carlos Bernal Barrionuevo","77969117Z","1458",3000,"4013554964220399");
        //        modelo.añadirTarjetas(new TarjetaCredito("Carlos Bernal Barrionuevo", "77969117Z", "1458", 3000, "4013554964220399"));
        //        modelo.añadirTarjetas(new TarjetaCredito("Edith Sandheaver", "27979803G", "3698", 2000, "5113872092370175"));
        //        modelo.añadirTarjetas(new TarjetaCredito("Kinga Kranoveter", "46758204D", "3248", 1500, "5102209252563195"));
        //        modelo.fireTableDataChanged();
        modelo.añadirTarjetas(nuevaTarjeta.getNuevaTarjeta());
        modelo.fireTableDataChanged();

        //Ejemplos tarjetas:
        //        1. Carlos Bernal Barrionuevo 77969117Z 1458 3000 4013554964220399
        //        2. Edith Sandheaver 27979803G 3698 2000 5113872092370175
        //        3. Kinga Kranoveter 46758204D 3248 1500 5102209252563195
    }//GEN-LAST:event_jbCrearActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        PedirDNI tarjetas = new PedirDNI(modelo.getListatarjetas());
        tarjetas.setVisible(true);
        modelo.setListatarjetas(tarjetas.eliminarTarjetas());
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGastosActionPerformed
        PedirDNI tarjetas = new PedirDNI(modelo.getListatarjetas());
        tarjetas.setVisible(true);
        modelo.setListatarjetas(tarjetas.eliminarTarjetas());
    }//GEN-LAST:event_jbGastosActionPerformed

    private void jbGetionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetionarActionPerformed

    }//GEN-LAST:event_jbGetionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirModificarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirModificarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirModificarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirModificarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirModificarTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGastos;
    private javax.swing.JButton jbGetionar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbTarjetas;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JMenuItem jmiCargarTarjetas;
    private javax.swing.JMenuItem jmiExportarTarjetas;
    // End of variables declaration//GEN-END:variables
}
