/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import libreria.Usuario;

/**
 *
 * @author deifont
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSaludar = new javax.swing.JButton();
        jlSaludo = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmUsuarios = new javax.swing.JMenu();
        jmiNuevoUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbSaludar.setText("Pulsar");
        jbSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaludarActionPerformed(evt);
            }
        });

        jlSaludo.setText("Hola, bienvenido a mi primera aplicación Swing");

        jtfNombreUsuario.setToolTipText("Escriba su nombre");
        jtfNombreUsuario.setPreferredSize(new java.awt.Dimension(200, 24));

        jmUsuarios.setText("Usuarios");

        jmiNuevoUsuario.setText("Nuevo");
        jmiNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoUsuarioActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiNuevoUsuario);

        jmbMenuPrincipal.add(jmUsuarios);

        jMenu2.setText("Edit");
        jmbMenuPrincipal.add(jMenu2);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlSaludo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSaludar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSaludar)
                    .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jlSaludo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaludarActionPerformed

        String nombre = jtfNombreUsuario.getText();

        if (nombre.isEmpty() || nombre.isBlank()) {
            String mensajeError = "Introduzca su nombre en el cuadro de texto";
            JOptionPane.showMessageDialog(rootPane, mensajeError, "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String mensaje = "Hola " + nombre + ".\n Bienvenido a mi primera aplicacion Swing.";
            jlSaludo.setText(mensaje);
            jlSaludo.setVisible(true);
        }


    }//GEN-LAST:event_jbSaludarActionPerformed

    private void jmiNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoUsuarioActionPerformed

        JDNuevoUsuario nuevoUsuario = new JDNuevoUsuario(this, true);
        nuevoUsuario.setVisible(true);

        if (nuevoUsuario.haAceptado()) {
            Usuario user = nuevoUsuario.getNuevoUsuario();
            this.jtfNombreUsuario.setText(user.getNombre());
        }

    }//GEN-LAST:event_jmiNuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jbSaludar;
    private javax.swing.JLabel jlSaludo;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiNuevoUsuario;
    private javax.swing.JTextField jtfNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        jlSaludo.setVisible(false);
    }
}
