
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAW-B
 */
public class jfOfuscarDesofuscar extends javax.swing.JFrame {

    /**
     * Creates new form jfOfuscarDesofuscar
     */
    public jfOfuscarDesofuscar() {
        initComponents();
        inicio();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMensajeInicial = new javax.swing.JLabel();
        jlMensaje = new javax.swing.JLabel();
        jlMensajeArchivo = new javax.swing.JLabel();
        jbOfuscar = new javax.swing.JButton();
        jbDesofuscar = new javax.swing.JButton();
        jlMensajeCambiado = new javax.swing.JLabel();
        jlMensaje2 = new javax.swing.JLabel();
        jlMensaje3 = new javax.swing.JLabel();
        jtfCaracteres = new javax.swing.JTextField();
        jmbMenú = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAbrir = new javax.swing.JMenuItem();
        jmiGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlMensajeInicial.setText("Elige un archivo en el botón \"Archivo\".");

        jlMensaje.setText("Mensaje dentro del archivo:");

        jbOfuscar.setText("Ofuscar");
        jbOfuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOfuscarActionPerformed(evt);
            }
        });

        jbDesofuscar.setText("Desofuscar");

        jlMensaje2.setText("Mensaje");

        jlMensaje3.setText("Introduzca el nº de caracteres:");

        jtfCaracteres.setText("jTextField1");
        jtfCaracteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCaracteresActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jmiAbrir.setText("Abrir");
        jmiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAbrir);

        jmiGuardar.setText("Guardar");
        jMenu1.add(jmiGuardar);

        jmbMenú.add(jMenu1);

        jMenu2.setText("Otros");

        jmiAyuda.setText("Ayuda");
        jmiAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAyudaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAyuda);

        jmbMenú.add(jMenu2);

        setJMenuBar(jmbMenú);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMensajeInicial)
                            .addComponent(jlMensaje)
                            .addComponent(jlMensajeArchivo)
                            .addComponent(jlMensajeCambiado)
                            .addComponent(jlMensaje2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbOfuscar)
                        .addGap(73, 73, 73)
                        .addComponent(jtfCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbDesofuscar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jlMensaje3)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlMensajeInicial)
                .addGap(18, 18, 18)
                .addComponent(jlMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMensajeArchivo)
                .addGap(45, 45, 45)
                .addComponent(jlMensaje3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOfuscar)
                    .addComponent(jbDesofuscar)
                    .addComponent(jtfCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMensaje2)
                .addGap(18, 18, 18)
                .addComponent(jlMensajeCambiado)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirActionPerformed
        JFileChooser jfc = new JFileChooser();

        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtroExtension = new FileNameExtensionFilter("Solo archivos txt", "txt");
        jfc.addChoosableFileFilter(filtroExtension);

        int opcion = jfc.showOpenDialog(this);
        seleccion();
        if (opcion == JFileChooser.APPROVE_OPTION) {
            String fichero = jfc.getSelectedFile().getAbsolutePath();
            jlMensajeInicial.setText(fichero);
            leerArchivo(jfc.getSelectedFile());
        } else {
            jlMensajeInicial.setText("No se ha cargado ningún archivo");
        }
    }//GEN-LAST:event_jmiAbrirActionPerformed

    private void jmiAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAyudaActionPerformed
        String mensaje = "Aplicación de prueba de Swing\nCreado por Carlos\n(c) 2023";
        String titulo = "AYUDA";

        JOptionPane.showMessageDialog(rootPane, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiAyudaActionPerformed

    private void jbOfuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOfuscarActionPerformed
        jlMensaje2.setVisible(true);
        jlMensaje2.setText("Mensaje ofuscado: "+jtfCaracteres.getText());
        jlMensajeCambiado.setText(ofuscar(jlMensajeInicial.getText(), Integer.parseInt(jtfCaracteres.getText())));
        jlMensajeCambiado.setVisible(true);
    }//GEN-LAST:event_jbOfuscarActionPerformed

    private void jtfCaracteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCaracteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCaracteresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfOfuscarDesofuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfOfuscarDesofuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfOfuscarDesofuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfOfuscarDesofuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfOfuscarDesofuscar().setVisible(true);
            }
        });
    }

    private void inicio() {
        jlMensaje.setVisible(false);
        jlMensajeArchivo.setVisible(false);
        jbDesofuscar.setVisible(false);
        jbOfuscar.setVisible(false);
        jlMensaje2.setVisible(false);
        jlMensajeCambiado.setVisible(false);
        jlMensaje3.setVisible(false);
        jtfCaracteres.setVisible(false);

    }

    private void seleccion() {
        jlMensaje.setVisible(true);
        jlMensajeArchivo.setVisible(true);
        jbDesofuscar.setVisible(true);
        jbOfuscar.setVisible(true);
        jlMensaje3.setVisible(true);
        jtfCaracteres.setVisible(true);
    }

    private void leerArchivo(File f) {
        if (f.exists()) {
            BufferedReader bf = null;
            try {
                bf = new BufferedReader(new FileReader(f));
                String cad;
                try {
                    while ((cad = bf.readLine()) != null) {
                        jlMensajeArchivo.setText(cad);
                        //System.out.println(cad);
                    }
                } catch (IOException ex) {
                    System.err.println("Ha ocurrido una excepción");
                }
            } catch (FileNotFoundException ex) {
                System.err.println("Ha ocurrido una excepción");
            } finally {
                try {
                    bf.close();
                } catch (IOException ex) {
                    System.err.println("Ha ocurrido una excepción");
                }
            }
        } else {
            System.out.println("El fichero no existe (cuidao con la extensión)");
        }
    }

    private static String ofuscar(String mensaje, int n) {
        String ofuscado = "";
        String cadena = ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890/*-+.'¡´{}()/&%$<>");
        int indice = n;
        System.out.println(indice + "indices");
        for (int i = 0; i < mensaje.length(); i++) {
            ofuscado += mensaje.substring(i, i + 1);
            for (int j = 0; j < n; j++) {
                for (int k = 0; k < n; k++) {
                    indice = ((int) Math.floor(Math.random() * (0 - cadena.length()) + cadena.length()));
                }
                ofuscado += cadena.substring(indice, indice + 1);
            }
        }
        return ofuscado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jbDesofuscar;
    private javax.swing.JButton jbOfuscar;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JLabel jlMensaje2;
    private javax.swing.JLabel jlMensaje3;
    private javax.swing.JLabel jlMensajeArchivo;
    private javax.swing.JLabel jlMensajeCambiado;
    private javax.swing.JLabel jlMensajeInicial;
    private javax.swing.JMenuBar jmbMenú;
    private javax.swing.JMenuItem jmiAbrir;
    private javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JMenuItem jmiGuardar;
    private javax.swing.JTextField jtfCaracteres;
    // End of variables declaration//GEN-END:variables

}
