
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAW-B
 */
public class EcuaciónPrimerGrado extends javax.swing.JFrame {

    /**
     * Creates new form EcuaciónPrimerGrado
     */
    public EcuaciónPrimerGrado() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jlPrimerNumero = new javax.swing.JLabel();
        jlSegundoNumero = new javax.swing.JLabel();
        jtfPrimerNumero = new javax.swing.JTextField();
        jtfSegundoNumero = new javax.swing.JTextField();
        jlResultado = new javax.swing.JLabel();
        jbCalcularResultado = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlPrimerNumero.setText("Introdúzca el primer número:");

        jlSegundoNumero.setText("Introdúzca el segundo número:");

        jtfPrimerNumero.setText("1 número");

        jtfSegundoNumero.setText("2 número");
        jtfSegundoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSegundoNumeroActionPerformed(evt);
            }
        });

        jlResultado.setText("jLabel3");
        jlResultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlResultadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jbCalcularResultado.setText("Calcular");
        jbCalcularResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSegundoNumero)
                    .addComponent(jlPrimerNumero)
                    .addComponent(jtfPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlResultado)
                    .addComponent(jbCalcularResultado))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlPrimerNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jlSegundoNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbCalcularResultado)
                .addGap(18, 18, 18)
                .addComponent(jlResultado)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlResultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlResultadoAncestorAdded

    }//GEN-LAST:event_jlResultadoAncestorAdded

    private void jbCalcularResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularResultadoActionPerformed
        String a = jtfPrimerNumero.getText();
        int n1 = Integer.parseInt(a);
        String b = jtfSegundoNumero.getText();
        int n2 = Integer.parseInt(b);
        if (n1<0) {
            String mensaje = "Debes introducir un numero válido";
            JOptionPane.showMessageDialog(rootPane, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int resultado = (-n1/n2);
            String mensaje = "El resultado es: " + resultado;
            jlResultado.setText(mensaje);
            jlResultado.setVisible(true);
        }    }//GEN-LAST:event_jbCalcularResultadoActionPerformed

    private void jtfSegundoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSegundoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSegundoNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcuaciónPrimerGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcuaciónPrimerGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcuaciónPrimerGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcuaciónPrimerGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcuaciónPrimerGrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton jbCalcularResultado;
    private javax.swing.JLabel jlPrimerNumero;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlSegundoNumero;
    private javax.swing.JTextField jtfPrimerNumero;
    private javax.swing.JTextField jtfSegundoNumero;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        jlResultado.setVisible(false);
    }
    
    private static boolean isNumeric(String str){    
        //return str != null && str.matches("[0-9.]")
        return false;
        //return str != null && str.matches("[0-9.]")
    }
}
