/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import libreria.Usuario;

/**
 *
 * @author DAW-B
 */
public class VentanaPricipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPricipal
     */
    public VentanaPricipal() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSaludar = new javax.swing.JButton();
        jlSaludo = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiNuevoUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jbSaludar.setText("Pulsar");
        jbSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaludarActionPerformed(evt);
            }
        });

        jlSaludo.setText("Hola, bienvenido a mi primera aplicación Swing");

        jtfNombreUsuario.setText("Escriba su nombre");
        jtfNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreUsuarioActionPerformed(evt);
            }
        });

        jmArchivo.setText("Archivo");
        jmArchivo.setToolTipText("");

        jmiNuevoUsuario.setText("Nuevo");
        jmiNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoUsuarioActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiNuevoUsuario);

        jMenuBar1.add(jmArchivo);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSaludo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSaludar)
                        .addGap(33, 33, 33)
                        .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSaludar)
                    .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jlSaludo)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaludarActionPerformed
        String nombre = jtfNombreUsuario.getText();
        if (nombre.isBlank() || nombre.isEmpty()) {
            String mensaje = "Introduce un nómbre valido";
            JOptionPane.showMessageDialog(rootPane, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String mensaje = "Hola " + nombre + " bienevenido a mi primera aplicacion Swing";
            jlSaludo.setText(mensaje);
            jlSaludo.setVisible(true);
        }
    }//GEN-LAST:event_jbSaludarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jtfNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreUsuarioActionPerformed

    private void jmiNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoUsuarioActionPerformed

        JDNuevoUsuario nuevoUsuario = new JDNuevoUsuario(this, true);
        nuevoUsuario.setVisible(true);
        if (nuevoUsuario.haAceptado()) {
            Usuario user = nuevoUsuario.getNuevoUsuario();
            this.jtfNombreUsuario.setText(user.getNombre());
        }
    }//GEN-LAST:event_jmiNuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbSaludar;
    private javax.swing.JLabel jlSaludo;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmiNuevoUsuario;
    private javax.swing.JTextField jtfNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        jlSaludo.setVisible(false); //para que no sea visible el jlLabenl
    }

}
