/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package holaswing;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author deifont
 */
public class jfHolaSwing extends javax.swing.JFrame {

    /**
     * Creates new form jfHolaSwing
     */
    public jfHolaSwing() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPulsar = new javax.swing.JButton();
        jlEtiqueta = new javax.swing.JLabel();
        jmbMenu = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiAbrir = new javax.swing.JMenuItem();
        jmiGuardar = new javax.swing.JMenuItem();
        jmAcciones = new javax.swing.JMenu();
        jmiPulsar = new javax.swing.JMenuItem();
        jmiAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbPulsar.setMnemonic('p');
        jbPulsar.setText("Pulsar");
        jbPulsar.setToolTipText("Haz click con el botón para mostrar un mensaje");
        jbPulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsarActionPerformed(evt);
            }
        });

        jlEtiqueta.setText("Hola que tal");

        jmArchivo.setMnemonic('a');
        jmArchivo.setText("Archivo");

        jmiAbrir.setText("Abrir");
        jmiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiAbrir);

        jmiGuardar.setText("Guardar");
        jmArchivo.add(jmiGuardar);

        jmbMenu.add(jmArchivo);

        jmAcciones.setMnemonic('c');
        jmAcciones.setText("Acciones");

        jmiPulsar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiPulsar.setMnemonic('p');
        jmiPulsar.setText("Pulsar");
        jmiPulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsarActionPerformed(evt);
            }
        });
        jmAcciones.add(jmiPulsar);

        jmiAyuda.setText("Ayuda");
        jmiAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        jmAcciones.add(jmiAyuda);

        jmbMenu.add(jmAcciones);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPulsar)
                    .addComponent(jlEtiqueta))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jbPulsar)
                .addGap(27, 27, 27)
                .addComponent(jlEtiqueta)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsarActionPerformed
        jlEtiqueta.setVisible(true);
    }//GEN-LAST:event_pulsarActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        String mensaje = "Aplicación de prueba de Swing\nCreado por JLBerenguel\n(c) 2021";
        String titulo = "AYUDA";

        JOptionPane.showMessageDialog(rootPane, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ayudaActionPerformed

    private void jmiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirActionPerformed
        JFileChooser jfc = new JFileChooser();

        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtroExtension = new FileNameExtensionFilter("Solo archivos txt", "txt");
        jfc.addChoosableFileFilter(filtroExtension);

        int opcion = jfc.showOpenDialog(this);
        
        if (opcion == JFileChooser.APPROVE_OPTION) {
            String fichero = jfc.getSelectedFile().getAbsolutePath();
            jlEtiqueta.setText(fichero);
        } else {
            jlEtiqueta.setText("No se ha cargado ningún archivo");
        }
    }//GEN-LAST:event_jmiAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfHolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfHolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfHolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfHolaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfHolaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbPulsar;
    private javax.swing.JLabel jlEtiqueta;
    private javax.swing.JMenu jmAcciones;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiAbrir;
    private javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JMenuItem jmiGuardar;
    private javax.swing.JMenuItem jmiPulsar;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        jlEtiqueta.setVisible(true);
        jlEtiqueta.setText("¡Esta es mi primera aplicación con Java Swing!");

    }
}
